name: OSV-Scanner

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  actions: read
  contents: read
  security-events: write

concurrency:
  group: osv-${{ github.ref }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  scan-main:
    if: ${{ github.event_name == 'push' }}
    uses: google/osv-scanner-action/.github/workflows/osv-scanner-reusable.yml@3adb4b14a2b0623876d18d863a498b785fb3752d # v2.3.8
    with:
      scan-args: |-
        --include-git-root
        -r
        ./

  scan-pr:
    if: ${{ github.event_name == 'pull_request' }}
    uses: google/osv-scanner-action/.github/workflows/osv-scanner-reusable-pr.yml@3adb4b14a2b0623876d18d863a498b785fb3752d # v2.3.8
    with:
      scan-args: |-
        --include-git-root
        -r
        ./
